create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  customer_name text not null,
  customer_phone text not null,
  customer_location text not null,
  items jsonb not null,
  payment text not null check (payment in ('UPI','COD')),
  note text default '',
  total numeric(10,2) not null,
  status text not null default 'NEW' check (status in ('NEW','ACCEPTED','PREPARING','READY','OUT_FOR_DELIVERY','COMPLETED','CANCELLED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_order_id_idx on public.orders(order_id);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
